name: ML Experiment Tracking

on:
  push:
    branches: main

jobs:
  run_experiment:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run MLflow experiment
      env:
        MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
      run: |
        mlflow run . --env-manager=local -e sample.py

    - name: Deploy to Dagshub
      env:
        DAGSHUB_API_KEY: ${{ secrets.DAGSHUB_API_KEY }}
      run: |
        dagshub model deploy
