name: ML Experiment Tracking

on: [push]

jobs:
  run_experiment:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Install pyenv
      run: |
        git clone https://github.com/pyenv/pyenv.git ~/.pyenv
        
    - name: Add pyenv to PATH
      run: echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.bashrc
      
    - name: Reload shell
      run: source ~/.bashrc
      
    - name: Install Python version
      run: pyenv install 3.8.9
      
    - name: Set global version
      run: pyenv global 3.8.9
      
    - name: Install mlflow
      run: pip install mlflow
      
    - name: Run MLflow experiment
      env:
        MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
      run: |
        mlflow run . -P alpha=0.5 -P beta=0.3 -e sample.py
